// Demo timeline: part order, durations, transitions.
// Edit this file to reorder/retime/skip parts.
export const TIMELINE = {
  parts: [
    { id: 'intro_logo',     dur: 6000,  transitionIn: 'fade',  transitionOut: 'flash' },
    { id: 'starfield',      dur: 14000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'copperbars',     dur: 16000, transitionIn: 'vhs',   transitionOut: 'flash' },
    { id: 'plasma',         dur: 14000, transitionIn: 'fade',  transitionOut: 'tear'  },
    { id: 'xorpattern',     dur: 12000, transitionIn: 'tear',  transitionOut: 'vhs'   },
    { id: 'bobs',           dur: 14000, transitionIn: 'vhs',   transitionOut: 'flash' },
    { id: 'fire',           dur: 14000, transitionIn: 'fade',  transitionOut: 'wipe'  },
    { id: 'bobsfire',       dur: 14000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'academy_techtech', dur: 12000, transitionIn: 'vhs',   transitionOut: 'vhs'   },
    { id: 'santa_multiplex',dur: 14000, transitionIn: 'vhs',   transitionOut: 'flash' },
    { id: 'metaballs',      dur: 14000, transitionIn: 'fade',  transitionOut: 'wipe'  },
    { id: 'rotozoom',       dur: 16000, transitionIn: 'wipe',  transitionOut: 'flash' },
    { id: 'checkerfloor',   dur: 14000, transitionIn: 'wipe',  transitionOut: 'vhs'   },
    { id: 'voxel_landscape',dur: 18000, transitionIn: 'vhs',   transitionOut: 'fade'  },
    { id: 'mandel',         dur: 22000, transitionIn: 'fade',  transitionOut: 'fade'  },
    { id: 'kaleido',        dur: 14000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'glenz',          dur: 16000, transitionIn: 'vhs',   transitionOut: 'flash' },
    { id: 'glenz4',         dur: 16000, transitionIn: 'wipe',  transitionOut: 'vhs'   },
    { id: 'mandel_deep',    dur: 16000, transitionIn: 'vhs',   transitionOut: 'fade'  },
    { id: 'waterripple',    dur: 14000, transitionIn: 'fade',  transitionOut: 'fade'  },
    { id: 'julia',          dur: 16000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'greetzscroller', dur: 36000, transitionIn: 'vhs',   transitionOut: 'fade'  },
    { id: 'tunnel',         dur: 16000, transitionIn: 'fade',  transitionOut: 'flash' },
    { id: 'sinescroller',   dur: 42000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'vectorcube',     dur: 16000, transitionIn: 'vhs',   transitionOut: 'wipe'  },
    { id: 'wire_tree',      dur: 16000, transitionIn: 'fade',  transitionOut: 'vhs'   },
    { id: 'battle',         dur: 23000, transitionIn: 'vhs',   transitionOut: 'fade'  },
    { id: 'snowglobe',      dur: 14000, transitionIn: 'fade',  transitionOut: 'fade'  },
    { id: 'fireworks',      dur: 16000, transitionIn: 'fade',  transitionOut: 'flash' },
    { id: 'outro_credits',  dur: 13000, transitionIn: 'fade',  transitionOut: 'fade'  },
  ],
};
